site_name: Weekly English Scripts

nav:
  - Home: index.md
  - Sales Funnel Discussion: sales-funnel.md
  - DeepSeek AI: deepseek-ai.md

theme:
  name: material
  features:
    - navigation.top
    - navigation.indexes
    - navigation.number
    - search.suggest
    - search.highlight

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mistrs2p/weekly-english-scripts

markdown_extensions:
  - toc:
      permalink: "#"

extra_css:
  - css/extra.css
use_directory_urls: false

