site_name: Weekly English Scripts
nav:
  - Home: index.md
  - Sales Funnel Discussion: sales-funnel.md
  - DeepSeek AI: deepseek-ai.md
theme:
  name: material
  # name: readthedocs


use_directory_urls: false

